import csv

web_apps = [
    ("Stripe", "Web App", "Clean typography and seamless animations"),
    ("Linear", "Web App", "Dark mode by default, high-performance UI"),
    ("Vercel", "Web App", "Minimalist, developer-focused aesthetic"),
    ("Figma", "Web App", "Real-time collaborative canvas with intuitive toolbars"),
    ("Notion", "Web App", "Block-based editing with clean monochrome layout"),
    ("Airbnb", "Web App", "Immersive imagery and map-based navigation"),
    ("Apple Music", "Web App", "Glassmorphism and vibrant color gradients"),
    ("Spotify", "Web App", "Dark theme with high-contrast album art"),
    ("Arc Browser", "Web App", "Sidebar navigation and customizable spaces"),
    ("Raycast", "Web App", "Command-line interface inspired quick actions"),
    ("Superhuman", "Web App", "Keyboard-first navigation and minimalist design"),
    ("Cron", "Web App", "Grid-based layout with precise time interactions"),
    ("Spline", "Web App", "Interactive 3D web experiences"),
    ("Framer", "Web App", "Visual canvas with advanced layout animations"),
    ("Loom", "Web App", "Floating overlay widgets and smooth transitions"),
    ("Discord", "Web App", "Server-channel hierarchy with gaming aesthetic"),
    ("Slack", "Web App", "Dense information architecture with sidebar categorization"),
    ("Github", "Web App", "Utilitarian design with clear diff visualizations"),
    ("Duolingo", "Web App", "Gamified UI with vibrant illustrations and characters"),
    ("CodeSandbox", "Web App", "Integrated development environment in browser"),
    ("Vimeo", "Web App", "Cinematic video player focused on content"),
    ("Pinterest", "Web App", "Masonry grid layout for image discovery"),
    ("Robinhood", "Web App", "Simplified financial charts and neon accents"),
    ("Coinbase", "Web App", "Clean cryptocurrency dashboard with soft shadows"),
    ("Miro", "Web App", "Infinite canvas with digital sticky notes"),
    ("Trello", "Web App", "Kanban board interface with drag-and-drop"),
    ("Asana", "Web App", "List and timeline views with status indicators"),
    ("Basecamp", "Web App", "Card-based project dashboard"),
    ("Typeform", "Web App", "One-question-at-a-time conversational interface"),
    ("Mailchimp", "Web App", "Playful branding with clear data visualizations"),
    ("Intercom", "Web App", "Floating chat widget and inbox layout"),
    ("Zendesk", "Web App", "Tabbed interface for multi-ticket management"),
    ("Shopify", "Web App", "E-commerce focused admin dashboard"),
    ("Stripe Atlas", "Web App", "Interactive forms and progress tracking"),
    ("Webflow", "Web App", "Visual code editor with complex property panels"),
    ("Canva", "Web App", "Template-driven design canvas with drag-and-drop"),
    ("Midjourney (Web)", "Web App", "Gallery-style image grid with prompt interface"),
    ("ChatGPT", "Web App", "Minimalist conversational chat interface"),
    ("Claude", "Web App", "Clean typography and artifact rendering"),
    ("Perplexity", "Web App", "Search-oriented interface with inline citations"),
    ("Gumroad", "Web App", "Creator-focused dashboard with brutalist influences"),
    ("Substack", "Web App", "Reading-focused layout with simple subscription flow"),
    ("Patreon", "Web App", "Creator feed and tier selection UI"),
    ("Twitch", "Web App", "Live stream player with high-density chat sidebar"),
    ("YouTube", "Web App", "Thumbnail grid and cinematic theater mode"),
    ("Netflix", "Web App", "Horizontal scrolling carousels with auto-playing previews"),
    ("Hulu", "Web App", "Hero banners with layered navigation"),
    ("HBO Max", "Web App", "Deep purple gradients and large typography"),
    ("Disney+", "Web App", "Brand hubs and animated hover states"),
    ("Prime Video", "Web App", "X-Ray overlay for actor/scene information"),
    ("Roku", "Web App", "Grid interface tailored for remote control"),
    ("Letterboxd", "Web App", "Poster grid layout with diary entries"),
    ("Strava", "Web App", "Activity feed with interactive maps and charts"),
    ("Peloton", "Web App", "Live leaderboard and metric overlays"),
    ("Calm", "Web App", "Soothing color palettes and ambient animations"),
    ("Headspace", "Web App", "Playful illustrations and circular progress bars"),
    ("Nike Training Club", "Web App", "High-contrast typography and instructional videos"),
    ("MyFitnessPal", "Web App", "Data-dense nutrition logging interface"),
    ("Oura", "Web App", "Ring data visualization with health scores"),
    ("Whoop", "Web App", "Recovery and strain metric dashboards"),
    ("Behance", "Web App", "Portfolio gallery with project deep-dives"),
    ("Dribbble", "Web App", "Shot grid with hover overlays for likes/saves"),
    ("Awwwards", "Web App", "High-end web design showcase with scoring UI"),
    ("Lapa Ninja", "Web App", "Landing page inspiration gallery"),
    ("Mobbin", "Web App", "Mobile UI pattern library with filtering"),
    ("Godly", "Web App", "Curated web design gallery with dark theme"),
    ("Siteinspire", "Web App", "Minimalist directory of web design"),
    ("Hoverstat.es", "Web App", "Alternative digital design interaction gallery"),
    ("Typewolf", "Web App", "Typography-focused design showcase"),
    ("Fontshare", "Web App", "Interactive font testing and specimen display"),
    ("Google Fonts", "Web App", "Typeface grid with dynamic sample text"),
    ("Material Design", "Web App", "Documentation site with interactive components"),
    ("Tailwind UI", "Web App", "Component gallery with copy-to-clipboard"),
    ("Radix UI", "Web App", "Unstyled accessible component primitives documentation"),
    ("Shadcn UI", "Web App", "Beautifully designed component copy-paste library"),
    ("Chakra UI", "Web App", "Accessible React component documentation"),
    ("Mantine", "Web App", "Comprehensive React components with dark mode"),
    ("Vite", "Web App", "Fast, modern development server documentation"),
    ("Next.js", "Web App", "Framework documentation with dark mode and search"),
    ("Nuxt", "Web App", "Vue framework site with vibrant green accents"),
    ("Svelte", "Web App", "Interactive tutorial REPL and documentation"),
    ("React", "Web App", "Interactive code examples and API reference"),
    ("Vue.js", "Web App", "Clean, approachable framework documentation"),
    ("Angular", "Web App", "Enterprise-focused framework site"),
    ("Three.js", "Web App", "3D examples gallery and documentation"),
    ("GSAP", "Web App", "Animation library showcase and forums"),
    ("Framer Motion", "Web App", "React animation documentation with interactive examples"),
    ("LottieFiles", "Web App", "Animation previewer and marketplace"),
    ("Spline Design", "Web App", "3D web design tool interface"),
    ("Rive", "Web App", "Interactive animation editor"),
    ("Descript", "Web App", "Text-based video/audio editing interface"),
    ("Riverside.fm", "Web App", "Browser-based recording studio UI"),
    ("SquadCast", "Web App", "Remote recording with green-room interface"),
    ("Zencastr", "Web App", "Podcast recording dashboard"),
    ("Restream", "Web App", "Multi-streaming destination toggles and chat"),
    ("StreamYard", "Web App", "Browser-based live streaming studio"),
    ("OBS Studio (Web)", "Web App", "Scene and source management interface"),
    ("Twitch Studio", "Web App", "Simplified streaming setup for beginners"),
    ("XSplit", "Web App", "Broadcaster UI with plugin architecture"),
    ("Lightstream", "Web App", "Cloud-based streaming studio")
]

games = [
    ("Elden Ring", "Game", "Intricate dark fantasy UI with minimal HUD"),
    ("Breath of the Wild", "Game", "Diegetic UI and unobtrusive compass"),
    ("Tears of the Kingdom", "Game", "Radial menus and ability selection wheels"),
    ("Ghost of Tsushima", "Game", "Guiding wind mechanic instead of minimap"),
    ("God of War (2018)", "Game", "Single-shot camera with Norse aesthetic menus"),
    ("God of War Ragnarok", "Game", "High-contrast accessibility options and clean skill trees"),
    ("Hades", "Game", "Isometric perspective with vibrant, stylized character portraits"),
    ("Hades II", "Game", "Witchcraft aesthetic with ethereal UI elements"),
    ("Hollow Knight", "Game", "Hand-drawn map UI and minimalist health masks"),
    ("Ori and the Blind Forest", "Game", "Glowing, ethereal UI elements and seamless menus"),
    ("Ori and the Will of the Wisps", "Game", "Expanded radial menus and improved map readability"),
    ("Celeste", "Game", "Pixel art UI with clear accessibility/assist options"),
    ("Cuphead", "Game", "1930s cartoon aesthetic in all menus and HUD"),
    ("Persona 5", "Game", "Highly stylized, dynamic menus with bold typography"),
    ("Persona 3 Reload", "Game", "Water-themed stylized menus and transitions"),
    ("Final Fantasy VII Remake", "Game", "Sleek, futuristic blue command menus"),
    ("Final Fantasy XVI", "Game", "High-fantasy elegant typography and skill rings"),
    ("Cyberpunk 2077", "Game", "Neon, glitch-aesthetic diegetic interfaces"),
    ("The Witcher 3", "Game", "Rustic inventory grids and bestiary layouts"),
    ("Red Dead Redemption 2", "Game", "Period-accurate typography and catalog menus"),
    ("Grand Theft Auto V", "Game", "In-game smartphone UI and radial weapon wheel"),
    ("Spider-Man (Insomniac)", "Game", "Sleek, tech-focused menus and social feed"),
    ("Spider-Man 2", "Game", "Seamless fast-travel UI and dual-protagonist switching"),
    ("Horizon Zero Dawn", "Game", "Holographic tribal aesthetic menus"),
    ("Horizon Forbidden West", "Game", "Improved holographic UI with extensive accessibility"),
    ("The Last of Us Part I", "Game", "Gritty, minimalist crafting UI"),
    ("The Last of Us Part II", "Game", "Industry-leading accessibility settings menus"),
    ("Uncharted 4", "Game", "Journal-based diegetic menus"),
    ("Bloodborne", "Game", "Gothic aesthetic inventory and status screens"),
    ("Demon's Souls (Remake)", "Game", "Modernized, high-resolution dark fantasy UI"),
    ("Sekiro: Shadows Die Twice", "Game", "Japanese calligraphy stylized menus"),
    ("Armored Core VI", "Game", "Utilitarian mech garage and HUD"),
    ("Overwatch", "Game", "Hero gallery and vibrant, clear ultimate meters"),
    ("Overwatch 2", "Game", "Refined, cleaner competitive UI"),
    ("Valorant", "Game", "Flat, modern tactical shooter HUD and buy menu"),
    ("CS:GO / CS2", "Game", "Utilitarian buy menu and clear crosshair options"),
    ("Apex Legends", "Game", "Ping system UI and dynamic inventory management"),
    ("Fortnite", "Game", "Constantly evolving, cartoony lobby and item shop UI"),
    ("Call of Duty: Warzone", "Game", "Military-style loadout menus and tactical map"),
    ("Destiny 2", "Game", "Cursor-based console menus and iconic director map"),
    ("Warframe", "Game", "Diegetic ship-based menus and complex modding UI"),
    ("Genshin Impact", "Game", "Clean, mobile-friendly gacha UI and elemental indicators"),
    ("Honkai: Star Rail", "Game", "Sci-fi sleek menus and turn-based battle timeline"),
    ("League of Legends", "Game", "Complex client with extensive stat tracking and shop"),
    ("Dota 2", "Game", "Highly customizable HUD and spectator interface"),
    ("Super Smash Bros. Ultimate", "Game", "Massive character select screen and bold percent meters"),
    ("Mario Kart 8 Deluxe", "Game", "Colorful, intuitive menus and clear position indicators"),
    ("Super Mario Odyssey", "Game", "Travel brochure map UI and snapshot mode"),
    ("Animal Crossing: New Horizons", "Game", "NookPhone diegetic apps and cute, bubbly menus"),
    ("Splatoon 3", "Game", "Graffiti-aesthetic menus and vibrant ink colors"),
    ("Zelda: Ocarina of Time", "Game", "Classic C-button item assignment UI"),
    ("Metroid Dread", "Game", "Sleek, high-tech map and suit upgrade menus"),
    ("Super Metroid", "Game", "Pioneering grid-based map interface"),
    ("Castlevania: Symphony of the Night", "Game", "Gothic inventory and map squares"),
    ("Stardew Valley", "Game", "Pixel art UI with intuitive farming/inventory grids"),
    ("Minecraft", "Game", "Blocky, scalable inventory and crafting grids"),
    ("Terraria", "Game", "Dense, hotbar-focused UI and crafting menus"),
    ("No Man's Sky", "Game", "Cursor-based menus and procedural discovery logs"),
    ("Subnautica", "Game", "Diegetic PDA and clean underwater HUD"),
    ("Outer Wilds", "Game", "Ship computer log and rumor map interface"),
    ("Disco Elysium", "Game", "Thought cabinet and text-heavy dialogue UI"),
    ("Baldur's Gate 3", "Game", "Complex CRPG hotbars, dice roll UI, and inventory"),
    ("Divinity: Original Sin 2", "Game", "Detailed character sheets and action point meters"),
    ("The Elder Scrolls V: Skyrim", "Game", "Constellation skill trees and minimalist compass"),
    ("Fallout 4", "Game", "Diegetic Pip-Boy interface and green monochrome HUD"),
    ("Mass Effect", "Game", "Dialogue wheel and sci-fi aesthetic"),
    ("Mass Effect 2", "Game", "Streamlined, sleeker Normandy terminal UI"),
    ("Halo: Combat Evolved", "Game", "Iconic shield meter and motion tracker HUD"),
    ("Halo Infinite", "Game", "Modernized Spartan HUD and clean multiplayer menus"),
    ("Doom (2016)", "Game", "Aggressive red UI and diegetic suit upgrades"),
    ("Doom Eternal", "Game", "Arcade-style resource meters and bright pop-ups"),
    ("Half-Life 2", "Game", "Minimalist, immersive HUD with amber text"),
    ("Portal", "Game", "Aperture Science sterile test chamber signage"),
    ("Portal 2", "Game", "Dynamic co-op ping system and clean menus"),
    ("Left 4 Dead 2", "Game", "Movie poster loading screens and clear health bars"),
    ("Team Fortress 2", "Game", "60s spy aesthetic menus and class selection"),
    ("Rocket League", "Game", "Sports-broadcast style scoreboards and replays"),
    ("FIFA 23 / EA Sports FC", "Game", "Tile-based menus and ultimate team card designs"),
    ("NBA 2K", "Game", "Broadcast presentation overlays and city maps"),
    ("Madden NFL", "Game", "Playcalling screens and franchise dashboards"),
    ("Gran Turismo 7", "Game", "Elegant, museum-like car collection menus"),
    ("Forza Horizon 5", "Game", "Festival-themed vibrant UI and extensive map filters"),
    ("Need for Speed Unbound", "Game", "Graffiti-style visual effects and street-art menus"),
    ("Microsoft Flight Simulator", "Game", "Aviation instrument overlays and globe map"),
    ("World of Warcraft", "Game", "Highly customizable MMORPG action bars"),
    ("Final Fantasy XIV", "Game", "Controller-friendly cross hotbar and clean chat logs"),
    ("Guild Wars 2", "Game", "Painterly UI aesthetic and dynamic event trackers"),
    ("The Sims 4", "Game", "Clean, minimalist build/buy mode menus"),
    ("Cities: Skylines", "Game", "Data-rich overlays and zoning tools"),
    ("Civilization VI", "Game", "Map-based icons and detailed tech trees"),
    ("Crusader Kings III", "Game", "Complex nested tooltips and parchment aesthetics"),
    ("Stellaris", "Game", "Sci-fi grand strategy dashboards and outliner"),
    ("Hearts of Iron IV", "Game", "WWII era map modes and production lines"),
    ("Age of Empires II", "Game", "Classic RTS command panel and minimap"),
    ("StarCraft II", "Game", "Sleek, responsive command card and wireframes"),
    ("Warcraft III", "Game", "Hero inventory and distinct faction UI themes"),
    ("XCOM 2", "Game", "Holographic tactical overlays and ant-farm base view"),
    ("Darkest Dungeon", "Game", "Gothic comic-book UI with stress meters"),
    ("Slay the Spire", "Game", "Clear card descriptions and intent indicators"),
    ("Inscryption", "Game", "Diegetic tabletop and escape room UI elements")
]

all_sources = web_apps + games

with open('c:/Users/SHIVEK/Pictures/Summer Internship/Coursera Web/Project/sources.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(["Source Name", "Type", "Key Aesthetic/UI Feature"])
    for source in all_sources:
        writer.writerow(source)

print(f"Generated sources.csv with {len(all_sources)} rows.")
